import { Product } from "@/lib/types";

export const products: Product[] = [
  {
    id: 1,
    slug: "iphone-13-pro-128",
    code: "AMZ-001",
    name: "iPhone 13 Pro 128GB",
    brand: "Apple",
    category: "Smartphones",
    price: 2199,
    oldPrice: 2599,
    status: "in_stock",
    shortDescription: "Flagship smartphone with ProMotion display.",
    description:
      "Tested Amazon return item in excellent technical condition. Battery diagnostics completed, camera and Face ID verified.",
    specs: {
      Display: "6.1\" OLED",
      Storage: "128 GB",
      Camera: "12 MP triple system",
      Battery: "3095 mAh",
    },
    images: ["/items/phone.svg", "/items/phone-alt.svg"],
    featured: true,
  },
  {
    id: 2,
    slug: "macbook-air-m2-256",
    code: "AMZ-002",
    name: "MacBook Air M2 256GB",
    brand: "Apple",
    category: "Laptops",
    price: 3299,
    oldPrice: 3799,
    status: "in_stock",
    shortDescription: "Ultralight laptop with Apple Silicon M2.",
    description:
      "Refurbished and tested. Keyboard, screen, ports, and thermals were checked by technician.",
    specs: {
      CPU: "Apple M2",
      RAM: "8 GB",
      Storage: "256 GB SSD",
      Display: "13.6\" Liquid Retina",
    },
    images: ["/items/laptop.svg", "/items/laptop-alt.svg", "/items/laptop-side.svg"],
    featured: true,
  },
  {
    id: 3,
    slug: "sony-wh-1000xm5",
    code: "AMZ-003",
    name: "Sony WH-1000XM5",
    brand: "Sony",
    category: "Audio",
    price: 899,
    status: "reserved",
    shortDescription: "Premium noise-canceling headphones.",
    description:
      "Original accessories included. Sound and ANC profile tested in studio environment.",
    specs: {
      Type: "Over-ear",
      Connection: "Bluetooth 5.2",
      Battery: "Up to 30h",
      NoiseCanceling: "Adaptive",
    },
    images: ["/items/headphones.svg"],
    featured: true,
  },
  {
    id: 4,
    slug: "playstation-5",
    code: "AMZ-004",
    name: "PlayStation 5",
    brand: "Sony",
    category: "Gaming",
    price: 2499,
    status: "in_stock",
    shortDescription: "Next-gen console with DualSense controller.",
    description:
      "Console has been cleaned and stress-tested. HDMI, Wi-Fi and controller connectivity verified.",
    specs: {
      Storage: "825 GB SSD",
      Resolution: "4K",
      FPS: "Up to 120",
      Ports: "USB-C, HDMI 2.1",
    },
    images: ["/items/console.svg"],
    featured: true,
  },
  {
    id: 5,
    slug: "dell-xps-15",
    code: "AMZ-005",
    name: "Dell XPS 15",
    brand: "Dell",
    category: "Laptops",
    price: 5499,
    status: "sold",
    shortDescription: "High-performance laptop for creators.",
    description: "Top condition body and display. Battery wear below expected average.",
    specs: {
      CPU: "Intel Core i7",
      RAM: "16 GB",
      Storage: "1 TB SSD",
      GPU: "RTX 4050",
    },
    images: ["/items/laptop-side.svg"],
  },
  {
    id: 6,
    slug: "samsung-galaxy-s23",
    code: "AMZ-006",
    name: "Samsung Galaxy S23",
    brand: "Samsung",
    category: "Smartphones",
    price: 1999,
    status: "in_stock",
    shortDescription: "Compact flagship with great camera system.",
    description: "Inspected and reset to factory settings. Display and camera passed full checks.",
    specs: {
      Display: "6.1\" AMOLED",
      Storage: "128 GB",
      Camera: "50 MP main",
      Battery: "3900 mAh",
    },
    images: ["/items/phone-alt.svg"],
  },
  {
    id: 7,
    slug: "jbl-bar-500",
    code: "AMZ-007",
    name: "JBL Bar 500",
    brand: "JBL",
    category: "Audio",
    price: 1299,
    status: "in_stock",
    shortDescription: "Soundbar with virtual Dolby Atmos.",
    description: "Cleaned and tested with HDMI ARC and Bluetooth pairing.",
    specs: {
      Channels: "5.1",
      Power: "590W",
      Connectivity: "Wi-Fi + Bluetooth",
      HDMI: "eARC",
    },
    images: ["/items/soundbar.svg"],
  },
  {
    id: 8,
    slug: "canon-eos-r50",
    code: "AMZ-008",
    name: "Canon EOS R50",
    brand: "Canon",
    category: "Photo & Video",
    price: 2899,
    status: "reserved",
    shortDescription: "Mirrorless camera for creators.",
    description: "Shutter count and sensor condition verified by service engineer.",
    specs: {
      Sensor: "24.2 MP APS-C",
      Video: "4K 30fps",
      Mount: "RF",
      Connectivity: "Wi-Fi + Bluetooth",
    },
    images: ["/items/camera.svg"],
  },
];

export const categories = Array.from(new Set(products.map((item) => item.category))).sort();
export const brands = Array.from(new Set(products.map((item) => item.brand))).sort();
